name: ecotrack
description: "An AI-powered sustainability tracker app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+4
  http: ^1.3.0
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.11
  mobile_scanner: ^2.0.0
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.8.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/images/waste_management.png
    - assets/images/carbon_footprint.png
    - assets/images/shopping.png
    - assets/images/community_events.png
    - assets/fonts/Cursive.ttf
    - assets/loading.gif
    
  fonts:
    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive.ttf
